name: Notify Discord on Issue #6 Updates

on:
  issues:
    types: [opened, edited, closed, reopened]
  issue_comment:
    types: [created, edited]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check and send to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          echo "Reading event data from GitHub..."
          PAYLOAD=$(cat "$GITHUB_EVENT_PATH")
          ISSUE_NUMBER=$(echo "$PAYLOAD" | jq '.issue.number')

          if [ "$ISSUE_NUMBER" = "6" ]; then
            ACTION=$(echo "$PAYLOAD" | jq -r '.action')
            TITLE=$(echo "$PAYLOAD" | jq -r '.issue.title')
            URL=$(echo "$PAYLOAD" | jq -r '.issue.html_url')
            BODY=$(echo "$PAYLOAD" | jq -r '.issue.body' | head -c 300)

            echo "Sending Discord webhook..."
            curl -H "Content-Type: application/json" \
              -X POST \
              -d "{\"content\": \"🛎️ **Issue #6 Update:** $ACTION\n**Title:** $TITLE\n**Link:** $URL\n**Snippet:** $BODY...\"}" \
              "$DISCORD_WEBHOOK"
          else
            echo "Not issue #6. Skipping."
          fi
